CREATE TABLE USERS(
    CUSTOMERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 100000, INCREMENT BY 1),
    EMAIL VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    PHONE VARCHAR(12),
    PASSWORD VARCHAR(255),
    CONSTRAINT primary_key PRIMARY KEY (CUSTOMERID)
);